name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: 📖 Translated Documents
    labels:
      - konjacbot
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🔧 CI/CD Updates'
    labels:
      - 'CI/CD'
  - title: '🧹 Maintenance & Chores'
    labels:
      - 'chore'
  - title: '🚀 Enhancements & Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '⚙️ Operational Changes'
    labels:
      - 'Operation'
  - title: '🔍 SEO Improvements'
    labels:
      - 'SEO'
  - title: '🧪 Tests & Coverage'
    labels:
      - 'Test'

exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES
