name-template: 'Release $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: 📖 Translated Documents
    labels:
      - konjacbot

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
no-changes-template: '- No changes listed'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes

  $CHANGES
