extends:
  - '@commitlint/config-conventional'
parserPreset:
  parserOpts:
    issuePrefixes:
      - '#'
rules:
  'references-empty':
    - 2
    - 'never'
  subject-case:
    - 2
    - 'never'
    - - 'start-case'
      - 'sentence-case'
      - 'pascal-case'
