name: Auto translation
on: push
defaults:
  run:
    shell: bash
env:
  diff_file: ".auto-translation-diff.txt"
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - run: ./scripts/translation/diff-docs.sh "${diff_file}"
      - run: cat "${diff_file}"