name: Create Release Note Workflow
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    name: Create Release note
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: false
          commitish: feature/#264-add-release-feature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
