name: Create Release Note Workflow
# on:
#   pull_request:
#     types:
#       - closed
#   workflow_dispatch:
on:
  pull_request:
    branches:
      - feature/#264-add-release-feature # マージ先ブランチを feature に限定
    types:
      - closed
  workflow_dispatch: # 手動実行用トリガー
jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.title, 'konjacbot')
    name: Create Release note
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
          publish: false
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
